GET http://localhost:8080/user/me
Accept: application/json
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTc2MzQzMTcxLCJleHAiOjE1NzcyMDcxNzF9.NY-NKd9akJeaaKvkjJOB9cyrD0rgOJ3lxc-WGiiDYAai4pepR3rKKhsNFG4Uh4cSklhiBQsuobQyDIc6lOENgQ
###