POST localhost:8080/auth/signup
Accept: application/json
Content-Type: application/json

{
  "name" : "Blendica Vlad",
  "username" : "blendicavlad",
  "email" : "blendicavlad@yahoo.com",
  "password" : "parola"
}

###